server:
  port: 8030

spring:
  application:
    name: connector
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #注册进Nacos
    sentinel:
      transport:
        port: 9999   #指定和Sentinel控制台交互的端口
        dashboard: localhost:8888  #Sentinel控制台服务地址
  redis:
    host: localhost
    port: 6379
    password: Dhj1314520
    database: 0

#激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true

rocketmq:
  name-server: localhost:9876
  producer:
    group: MSG_GROUP

netty:
  port: 9000