server:
  port: 9401
spring:
  cache:
    redis:
      cache-null-values: true
      key-prefix: 'casbin:springboot:'
      time-to-live: 1000
      use-key-prefix: true
    type: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      jdbc-url: jdbc:mysql://localhost:3306/mychat?characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      password: Dhj1314520
      pool-name: CASBIN-HIKARICP
      username: root
    jdbc-url: jdbc:mysql://localhost:3306/mychat?characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    password: Dhj1314520
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/mychat?characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
  application:
    name: user-auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    port: 6379
    host: localhost
    password: Dhj1314520

management:
  endpoints:
    web:
      exposure:
        include: "*"

casbin:
  autoSave: true
  enableCasbin: true
  enableWatcher: false
  exception: removePolicyFailed
  initializeSchema: create
  model: classpath:rbac_model.conf
  policy: classpath:rbac_policy.csv
  storeType: jdbc
  useDefaultModelIfModelNotSetting: true
  useSyncedEnforcer: false
  watcherType: redis


