server:
  port: 8020

spring:
  application:
    name: chat-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #注册进Nacos
  datasource:
    #mysql
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mychat?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 112.74.175.57
    port: 6379
    password: Chen13058191889
    database: 0

rocketmq:
  name-server: localhost:9876

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.tojintao.model
